### ISSUE TITLE
puppet-chrony should support configurable leap second handling

### ISSUE THREAD

**Issue by elfchief** [aboe76/puppet-chrony#19]
Newer versions of chrony have added the "slew" leap second handling mode, which I suspect is becoming pretty popular (since it handles them smoothly, rather than doing the step-back-in-time that it otherwise does)

A kind of typical leap second config for this looks like this in the chrony config:

  leapsecmode slew
  maxslewrate 1000
  smoothtime 400 0.001 leaponly

Those default values are probably reasonable for many people, though making the values configurable should be easy. Do note that maxslewrate is a global value, but that the smoothtime values, if there is a 'leaponly' suffix, are specific to leap-second handling, so should probably be named appropriately.

Thanks!

**Comment by othalla** [comment]
Hello,
Did could you test it ?
seems interesting

**Comment by aboe76** [comment]
@elfchief could you create a PR for this?

**Comment by elfchief** [comment]
I could probably put something together, sure.

What do you think is the right way to handle the parameters for this? The `maxslewrate` and `smoothtime` config settings are useful outside of leap seconds, but are currently not set/used by the module. Should we expose those settings individually? Add the ability to just add arbitrary values to the config file? Add a boolean for leap second smears which just inserts the above config verbatim (it's the recommended config, but might not be appropriate for everyone)? Add multiple parameters for mode, max slew rate, and smoothtime?

(Yet another programming problem where actually writing the code is the easy part!)

**Comment by aboe76** [comment]
@elfchief I think the best approach is to have the variables exposed individually and use params.pp to fill it with the recommended defaults. 

and having a boolean true or false to set them or not.
