### ISSUE TITLE
Additional parameters needed: deny, enable_lock_all, mailonchange

### ISSUE THREAD

**Issue by grbailey66** [aboe76/puppet-chrony#20]
Please add parameters to this module:
1) **deny (array)**  - similar to allow -- complementary option
2)  **enable_lock_all**  => if true, set "lock_all" to keep chronyd from swapping to disk
3) **mailonchange** =>  we have had issues with our internal ntp servers drifting and VM hang/restarts
  getting a notice when a host suffers an exceptional sync diff is handy.

**Comment by othalla** [comment]
Hello, added some params https://github.com/aboe76/puppet-chrony/pull/25

**Comment by aboe76** [comment]
merged #25

**Comment by othalla** [comment]
@aboe76  thank you for merging my PR again :p

**Comment by aboe76** [comment]
@othalla can you test if this formula can be used with a newer version of stdlib?
would like to update the metadata.json,

**Comment by othalla** [comment]
Hi, sorry for this late reply, i'll check this out and give some update once done!

**Comment by aboe76** [comment]
@othalla thanks

**Comment by othalla** [comment]
i've checked, I'm currently running stdlib 4.25.1 with no issue :)

**Comment by aboe76** [comment]
@othalla thanks will update the metadata.json accordingly
