### ISSUE TITLE
Document "port" setting

### ISSUE THREAD

**Issue by olifre** [aboe76/puppet-chrony#29]
By default, `port` is set to `0` (good idea!). 
However, the examples still show a simple server configuration only specifying `queryhosts`. Without setting `port` to something different from `0`, server mode will still not work. 
A hint on this in the readme (or maybe even a `warn` if `queryhosts` is specified but `port=0`) would be very helpful,

**Comment by aboe76** [comment]
@olifre could you make a PR for this?

**Comment by olifre** [comment]
@aboe76 Sure! Which approach do you prefer:
1. A `notify` resource with `loglevel => 'alert' if `queryhosts` is set, but `port` is still at `0`. 
2. A `warn()` if `queryhosts` is set, but `port` is still at `0`. 
3. A `fail()` if `queryhosts` is set, but `port` is still at `0`. 
4. An explanation in the `README`. 
5. A combination of some of these.
?

**Comment by aboe76** [comment]
@olifre this is what I think is the best approach:
add explanation to ```README```
and ```fail()``` if ```queryhosts``` is set, but port is still at ```0```

This ensures that you have a working config as intended the ```fail``` will explain what's wrong.
