### ISSUE TITLE
Add tags for each version

### ISSUE THREAD

**Issue by AndreasPfaffeneder** [aboe76/puppet-chrony#34]
Hello,

this module looks like it does what it advertises. Could you please add tags for each release so we can have a local mirror of your repository and use a specific version of your module? 
Using commits as anchor for r10k works most of the time, but sometimes things are being re-based causing commits to  vanish.

Thanks
Andreas

**Comment by aboe76** [comment]
@AndreasPfaffeneder I have never used tags so if you have a easy manual on how to implement this, 
please enlighten me.

**Comment by AndreasPfaffeneder** [comment]
This depends on your tools, but basically the workflow would be like this:

1. You decide to increment your version number, i.e. make a release, e.g.: 3.1
2. In your git-client you add a tag: git tag -a v0.2.3 -m "releaseing 0.2.3"
3.) Push that that to origin: gut push --tags (all) or git push origin v0.2.3 (single one)

**Comment by aboe76** [comment]
@AndreasPfaffeneder I will try this the next version update of this module.

**Comment by kenyon** [comment]
@aboe76 you can tag previous releases too. Just tag the commit corresponding to the release version number (`git tag -a v0.x.y <commit>`), and `git push --tags`.

**Comment by aboe76** [comment]
I have some time next week, will try to add them @kenyon thanks for the info.

**Comment by aboe76** [comment]
@AndreasPfaffeneder and @AndreasPfaffeneder added version tags to all commits when I released it to the forge.

**Comment by AndreasPfaffeneder** [comment]
Thank you! Please keep this up for the future, very appreciate that! :)
