### ISSUE TITLE
update metadata to remove puppet-stdlib dependency

### ISSUE THREAD

**Issue by vchepkov** [aboe76/puppet-chrony#42]
I can submit a simple PR to update version in metadata.json, but I think the more proper fix would be to remove dependency on stdlib altogether. Unless I missed it, I don't see any stdlib functions or types that module uses.

**Comment by aboe76** [comment]
Please create a pr with your proper fix, I will merge it.

**Comment by vchepkov** [comment]
PR #43 has been created

**Comment by aboe76** [comment]
pushed new version 0.2.6 on forge
