### ISSUE TITLE
Please allow using pool instead of just server

### ISSUE THREAD

**Issue by thomasgoirand** [aboe76/puppet-chrony#53]
Hi,

FYI, I've packaged your puppet module, which is now available in Debian:
https://packages.debian.org/search?keywords=puppet-module-aboe-chrony

I'm happy of your module, and I use it in production (together, with a lot of other modules, I'm using it to setup OpenStack). Though, in /etc/chrony/chrony.conf, it's normally possible to do:

pool pool.example.com iburst

instead of:

server pool.example.com iburst

though this puppet module doesn't allow it. Could you please add the feature? It'd be great to just have a flag to be able to select that.

Cheers,

Thomas

**Comment by aboe76** [comment]
No problem, if you want you can create a PR and I will update the module

**Comment by alexjfisher** [comment]
Isn't this already fixed in https://github.com/aboe76/puppet-chrony/pull/38 ?

**Comment by alexjfisher** [comment]
As pointed out [here](https://github.com/aboe76/puppet-chrony/pull/38#issuecomment-496036329), the docs weren't updated though.

**Comment by aboe76** [comment]
@alexjfisher thank you.
