### ISSUE TITLE
Missing a tag for v0.3.2

### ISSUE THREAD

**Issue by initrd** [aboe76/puppet-chrony#66]
[Puppet Forge](https://forge.puppet.com/aboe/chrony/changelog) and CHANGELOG.md list release v0.3.2 but it isn't tagged in git. Could you please tag the release so we can anchor in our submodules. Thanks!

**Comment by aboe76** [comment]
@initrd sorry forgot to tag the release

**Comment by aboe76** [comment]
fixed it
