### ISSUE TITLE
Incompatible with future parser

### ISSUE THREAD

**Issue by jflorian** [aboe76/puppet-chrony#8]
I had to apply the following:

diff --git forge_modules/chrony/manifests/config.pp forge_modules/chrony/manifests/config.pp
index 9a750aa..1d8fe63 100644
--- forge_modules/chrony/manifests/config.pp
+++ forge_modules/chrony/manifests/config.pp
@@ -3,7 +3,7 @@ class chrony::config inherits chrony {
     ensure   => file,
     owner    => 0,
     group    => 0,
-    mode     => 0644,
+    mode     => '0644',
     content  => template($config_template),
     notify   => Service['chrony'],
   }

to avoid:

Warning: Non-string values for the file mode property are deprecated. It must be a string, either a symbolic mode like 'o+w,a+r' or an octal representation like '0644' or '755'.
   (at /usr/share/ruby/vendor_ruby/puppet/type/file/mode.rb:69:in `block (2 levels) in <module:Puppet>')

**Comment by aboe76** [comment]
fixed with version 0.1.1
